name: mysql_sink
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: Name of the input topic to listen to.
    defaultValue: hard-braking
  - name: mysql_server
    inputType: FreeText
    multiline: false
    defaultValue: mysql
  - name: mysql_db
    inputType: FreeText
    multiline: false
    defaultValue: quix
  - name: mysql_user
    inputType: FreeText
    multiline: false
    defaultValue: quix
  - name: mysql_password
    inputType: Secret
    multiline: false
    defaultValue: mysql_pwd
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
