name: Grafanaasdasdasd
language: docker
variables:
  - name: GF_SECURITY_ADMIN_PASSWORD
    inputType: Secret
    description: Password for the admin user
    defaultValue: ADMIN_PASSWORD
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: The optional InfluxDB Token to use
    defaultValue: INFLUXDB_ADMIN_TOKEN
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: grafana
