# Use official Python image
FROM python:3.10-slim

# Set environment variables for non-interactive setup and unbuffered output
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    PYTHONPATH="/app" \
    PORT=80 \
    MAINAPPPATH="/app"

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements to leverage Docker cache
COPY requirements.txt "${MAINAPPPATH}/requirements.txt"
            
# Install dependencies without caching
RUN pip install --no-cache-dir -r "${MAINAPPPATH}/requirements.txt"

# Copy the rest of the application
COPY . "${MAINAPPPATH}/"

# Command to run the server
CMD python main.py --quix-token "${pat_token}" --quix-workspace "${Quix__Workspace__Id}" --quix-base-url "${Quix__Portal__Api}" --port 80
