name: mysql
language: docker
variables:
  - name: MYSQL_ROOT_PASSWORD
    inputType: Secret
    description: The rootpassword to initialize mysql with
    required: true
  - name: a
    inputType: Secret
    description: The root password to initialize MongoDB with
    defaultValue: influx_pwd
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
