name: mysql
language: docker
variables:
  - name: MYSQL_ROOT_PASSWORD
    inputType: Secret
    multiline: false
    description: The rootpassword to initialize mysql with
    defaultValue: mysql_pwd
    required: true
  - name: MYSQL_DATABASE
    inputType: FreeText
    description: DB Name
    defaultValue: quix
    required: true
  - name: MYSQL_USER
    inputType: FreeText
    description: Admin user
    defaultValue: quix
    required: true
  - name: MYSQL_PASSWORD
    inputType: Secret
    multiline: false
    description: Admin password
    defaultValue: mysql_pwd
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
